### ISSUE TITLE
ایجاد یکباره همه دایرکتوری ها

### ISSUE THREAD

**Issue by jebraili** [idel327/laravel-modular#5]
سلام
ممنون از پکیج خوبی که نوشتین
یه سوال: آیا کامندی داره که همه دایرکتوری ها و فایل های یک ماژول رو هنگام ایجاد ماژول ایجاد کنه؟

**Comment by idel327** [comment]
سلام دوست عزیز.
در حال حاضر بهترین گزینه اینه که از دستور php artisan make:module blog --normal استفاده کنید تا ماژول متوسطی رو بسازید
ولی در اسرع وقت حتما کامندی به پکیج اضافه میشه قابلیت اینو داشته باشه همه چیو به صورت پیش فرض ایجاد کنه و در serviceprovider تنظیماتشونو انجام بده

**Comment by idel327** [comment]
دستور php artisan make:module blog --full اضافه شد
